name: "Save Tweets"

on:
  schedule:
    - cron: "0 */6 * * *" #6時間ごとに実行

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y_%m_%d_%H')" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          python -m unidic download

      - name: Create dot env file
        shell: bash
        run: |
          touch .env
          echo "CK=${{ secrets.CK }}" >> .env
          echo "CS=${{ secrets.CS }}" >> .env
          echo "AT=${{ secrets.AT }}" >> .env
          echo "AS=${{ secrets.AS }}" >> .env
          echo "BT=${{ secrets.BT }}" >> .env

      - name: Run save.py
        run: |
          python ./save.py

      - name: git setting
        run: |
          git config --local user.email "52403688+yashikota@users.noreply.github.com"
          git config --local user.name "yashikota"

      - name: Commit files
        run: |
            git add .
            git commit -m "save tweets ${{ env.CURRENT_DATETIME }}"
            git pull
            git push origin master
